### ISSUE TITLE
[Suggestion] Add Bedrock Item

### ISSUE THREAD

**Issue by A5ho9999** [TheCSDev/mc-better-stats#14]
**Describe the solution you'd like**
Add Bedrock Item Support as it is supported in vanilla stats

**Comment by TheCSDev** [comment]
Hello. Thank you for your suggestion, but bedrock already does show up in the item stats as seen below:<br/>
<details>
    <summary><i>Click here to see the image</i></summary>
    I have tested the mod by dropping a bedrock, and picking it back up (creative mode). Also, please excuse the custom texture pack I use.<br/>
    <image src="https://user-images.githubusercontent.com/66475965/197381356-7286fc52-b0b2-4e18-af27-64cac9351249.png"/>
</details>
<h4>Here are a few tips to help you troubleshoot your issue:</h4>

1. Statistics only ever update when in surival mode (this behavior is controlled by the game itself, not the mod)
2. `Bedrock` will only show up when it is `Mined` (mined refers to via a tool/fist, which is impossible), `Crafted` (impossible unless a data-pack allows it), `Picked Up` (impossible without you or someone else using creative), `Dropped` (impossible unless you picked one up), `Broken` (bedrock doesn't have durability, as it is not a tool, so impossible)
3. As seen in the `Point 2.`, it is impossible to meet any of the criteria for it showing up in survival mode.
4. But what if you used a glitch to break a bedrock block? That doesn't count. The `Times Mined` criteria is only met when the block is mined with a fist and/or a tool (which is impossible). Any and all behaviors of how the statistics are being tracked (including this behavior) are all controlled by the game itself, and not the mod. All the mod does is display those statistic values in a better way.
5. But what if you took a bedrock from a chest or a creative inventory? Those don't count as "Picked Up" or any other stat (and of course, that behavior too is controlled by the game itself).
6. But you already managed to meet one of the criteria mentioned in `Point 2.`, and it is still not showing up? Please make sure there aren't any other installed mods out there that for some reason prevent the bedrock from showing up and/or being tracked as a statistic. Alternatively, you may submit a bug report (provided you actually manage find the thing causing the bug, and then report it).
7. I don't know what else to come up with in this list. Please try creating a new test creative world, then take a bedrock, drop it, and then pick it back up. After that, check the item stats again, and then let me know if you saw bedrock show up.

Hopefully the list of tips helps. Have a great day.
