### ISSUE TITLE
Smooth Scrolling

### ISSUE THREAD

**Issue by RinixGG** [TheCSDev/mc-better-stats#15]
Could you add smooth scrolling to "General" and "Items" tabs

**Comment by TheCSDev** [comment]
Hello, and thank you for the suggestion. I am currently working on another version for the mod. So in the meantime, I will try to squeeze that feature in if I get the time to. Have a great day.

**Comment by TheCSDev** [comment]
Hello. I have just finished implementing that feature for the next Better Stats version. Thank you for your suggestion. There still is a bunch of other things that need taking care of before the next release tho. Have a great day again.

**Comment by TheCSDev** [comment]
I'll close the issue here so as to update the milestone progress bar.
