### ISSUE TITLE
Add support for polymer

### ISSUE THREAD

**Issue by BlueGamingCat1** [TheCSDev/mc-better-stats#2]
Some servers only have custom items running on the server and send that to the client with polymer. So some of the screens show incorrectly. Was wondering if you could add polymer support then.

Actually unsure if this is how it works or if it is possible. Just thought I would mention it.

**Comment by TheCSDev** [comment]
Hello. Thank you for your suggestion. This is the first time I heard about the mod you mentioned. I will take a look at it when I get the chance to. In the meantime, as far as I understood, this mod creates server-side items/mobs that in a way that doesn't require clients to install mods to interact with. If this is the case, do you know if the said mod keeps track of player interaction statistics with said items/mobs. If so, then maybe it is possible.

**Comment by BlueGamingCat1** [comment]
I don't really know if it is possible sadly, I talked a bit with the polymer dev (Patbox) and I think polymer would have to sync that for your mod, don't quote me on that though. But if the server hands out the mod and requires it client side it should work so that's nice.

Here is a snippet of the conversation:
![PolymerDev-BetterStats](https://user-images.githubusercontent.com/82487425/188330041-e1c7b001-c65a-4f11-9217-9569d90b3d99.png)

**Comment by TheCSDev** [comment]
Hello again. I have decided to close this issue as there is no need to keep it open anymore. Have a good day once again if you are reading this.
